apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao-de-temperatura
spec:
  selector:
    matchLabels:
      app: web-page
  template:
    metadata: 
      labels:
        app: web-page
    spec:
      containers:
        - name: conversao-de-temperatura
          image: audreycosta/conversao-temperatura
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector: 
    app: web-page
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort